# Generated by Django 3.0.8 on 2020-07-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0002_men_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
