# Generated by Django 3.0.8 on 2020-07-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0003_men_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='Price_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='men',
            name='discount',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='men',
            name='price_now',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='men',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='men',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
