# Generated by Django 3.0.8 on 2020-07-30 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='men.Category'),
            preserve_default=False,
        ),
    ]
